#!/usr/bin/env node
// Generates a SQL file from JSON dumps in ./data/*.json (one file per entity).
// Apply with:  wrangler d1 execute partsync --remote --file=./data/_import.sql
//
// Expected files (each containing a JSON array of records):
//   data/part_orders.json
//   data/return_logs.json
//   data/vendors.json
//   data/routing_rules.json
//   data/technician_logs.json
//   data/users.json     (optional — if you're seeding users)
//
// Each record should already have an `id` (UUID). Booleans → 0/1, arrays → JSON strings.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data');
const OUT_FILE = join(DATA_DIR, '_import.sql');

const TABLES = {
  part_orders: ['id','part_number','purchase_order','vendor_id','vendor_name','vendor_order_number','tracking_number','estimated_delivery','customer_email','customer_name','status','notification_sent','notes','part_category','created_by','created_date','updated_date'],
  return_logs: ['id','part_number','purchase_order','vendor_id','vendor_name','issue_type','photo_url','description','log_status','reported_by','order_id','created_by','created_date','updated_date'],
  vendors: ['id','name','key_contact','email','phone','directory','part_categories','avg_score','total_orders','is_active','created_by','created_date','updated_date'],
  routing_rules: ['id','rule_name','description','part_category','vendor_id','vendor_name','priority','is_active','created_by','created_date','updated_date'],
  technician_logs: ['id','technician_name','technician_email','quarter','year','quarter_number','return_count','notes','created_by','created_date','updated_date'],
  users: ['id','email','password_hash','full_name','role','vendor_id','email_verified','created_date','updated_date'],
};
const BOOL_FIELDS = new Set(['notification_sent','is_active','email_verified']);
const JSON_FIELDS = new Set(['part_categories']);

const sqlLiteral = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

const lines = ['-- Auto-generated by scripts/import-to-d1.mjs', 'BEGIN TRANSACTION;'];
for (const [table, cols] of Object.entries(TABLES)) {
  const path = join(DATA_DIR, `${table}.json`);
  if (!existsSync(path)) {
    console.warn(`skip ${table}: ${path} not found`);
    continue;
  }
  const rows = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(rows)) {
    console.error(`${table}: expected JSON array`);
    process.exit(1);
  }
  for (const row of rows) {
    const values = cols.map((c) => {
      let v = row[c];
      if (BOOL_FIELDS.has(c) && typeof v === 'boolean') v = v ? 1 : 0;
      if (JSON_FIELDS.has(c) && (Array.isArray(v) || (typeof v === 'object' && v !== null))) v = JSON.stringify(v);
      return sqlLiteral(v);
    });
    lines.push(`INSERT OR REPLACE INTO ${table} (${cols.join(',')}) VALUES (${values.join(',')});`);
  }
  console.log(`${table}: ${rows.length} rows`);
}
lines.push('COMMIT;');
writeFileSync(OUT_FILE, lines.join('\n') + '\n');
console.log(`\nWrote ${OUT_FILE}\nApply with:\n  wrangler d1 execute partsync --remote --file=${OUT_FILE}`);
